const NOT_VALIDE_NAME = "NO_VALIDE_NAME";
const NULL_POST = "NULL_POST";
const UNVALID_PASSWORD_LENGTH = "UNVALID_PASSWORD_LENGTH";
module.exports = {
  NOT_VALIDE_NAME,
  NULL_POST,
  UNVALID_PASSWORD_LENGTH,
};
